### PR TITLE
Submitions: MEGA-ACE HACKATHON TECHNICAL CHALLENGE 

### PR DESCRIPTION
**Pull request by nabetse00**
This is the repo i used to submit  Technical Challenges solutions:

# Beginner Level
- Completed: [Developer's helper](https://github.com/mega-ace-hackathon/first-hackathon/blob/main/DevelopersHelper/README.md)
- Conpleted: [One-stop NFT Creator](https://github.com/mega-ace-hackathon/first-hackathon/blob/main/OneStopNFTCreator/README.md)
# Medium Level
- Partial: [Tic-tac-toe smart contract champion](https://github.com/mega-ace-hackathon/first-hackathon/blob/main/TicTacToe/README.md)
- Complete: [Box-based indexing](https://github.com/mega-ace-hackathon/first-hackathon/blob/main/BoxBasedIndexing/README.md)

### CODE REVIEW

**Comment by Sam2much96** [comment]
Hello @nabetse00 , I don't think participants were supposed to submit a pull request to the main repository. The instructions were that all submissions should be done on mega Ace website. Participants Submit both the repository url and the commit hash on mega Ace website.

**Comment by nabetse00** [comment]
Hello @Sam2much96, so i should close the pull request ?

**Comment by Sam2much96** [comment]
Probably? I doubt the core devs would merge the Pull Request into the Master branch

**Comment by nabetse00** [comment]
ok ! i ll close it !

**Pull request closed without merging**
